### ISSUE TITLE
Firmware Update 550 Stable

### ISSUE THREAD

**Issue by ptr1337** [ttabi/linux-firmware#1]
Hi,

Would it be possible to update the nvidia gsp firmware into the upstream linux-firmware repo?
Currently the new Super GPUs are not supported by the 535 Firmware, which is currently in the repo.

Also the new stable nvidia is 550, so i think it would be good to update it.

CC: @ttabi

**Comment by ttabi** [comment]
That repo is used exclusively by Nouveau.  The driver itself would need to be updated first to use r550.  You would need to ask the Nouveau developers to do that first, or you can do it and submit patches.  But updating linux-firmware is the last step, not the first step.
